config/routes.rb
Rails.application.routes.draw do
 

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'histories/index'

  get 'references/new'
  get 'references/edit'
  get 'references/show'

  get 'stats/show'

  get 'facts/new'

  get 'children/new'

  get 'users/new'
  get 'users/create'
  get 'users/show'
  
  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy' 
  
  get   'how_it_works' => 'static_pages#how_it_works'
  get   'about' => 'static_pages#about'

  resources :users
  resources :children
  resources :facts
  resources :references, only: [:new, :create, :edit, :update, :index]
  resources :histories, only: [:index]
  resources :subscriptions, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  root 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
  <div class="center jumbotron">
    <div class="container">
       <div class="col-md-6" valign="center">
        <h3 align="left"><%= image_tag("iana.jpg", size: "200x150") %> &nbsp;&nbsp; Iana </h3>
        <br>
        <p align="left">Iana is the mom of two curious kiddos: Alec and Maya. Iana is passionate about educating young minds. 
        For years, she worked on developing educational software for school aged kids. She created Curious Tots to get toddlers and 
        preschoolers excited about science and learning.</p>
      </div>
       <div class="col-md-6">
        <h3 align="left"><%= image_tag("alec.jpg", size: "150x150") %> &nbsp;&nbsp; Alec </h3>
        <br>
        <p align="left"> Alec is the original Curious Tot and the inspiration behind this website. He LOVES animals and is a 
        walking encyclopedia of animal facts. Many of the facts on Curious Tots were inspired by him. When Alec grows up he wants 
        to be a daddy and a computer programmer. 
        </p>
      </div>
      <div class="container">
      <div class="col-md-12">
        <h3 align="left"><%= image_tag("robins_nest.jpg", size: "150x150") %> &nbsp;&nbsp; Our Story </h3>
        <br>
        <p align="left">
        The idea for Curious Tots was born on a lazy spring afternoon. Iana and then 2 year old  
        Alec were relaxing in their backyard when they noticed a robin's nest in a nearby tree. Iana explained to Alec that the 
        mommy bird made the nest and laid eggs in it. She sits on the eggs to keep them warm and then baby birds hatch from the eggs.
        <br><br>
        Alec was fascinated! As soon as Iana finished telling him the story he said "Talk about baby birds again!". This went on 
        for a while. :) As Iana was re-telling the story, she realized that young children are incredibly curious about the world 
        around them. Yet most children's science books are too advanced for toddlers and preschoolers. She created Curious Tots to give
        young kids an early exposure to science. She hopes that these simple and fun facts inspire a life-long love of science.
        </p>
      </div>
      </div>
    </div>
  </div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <% if admin_user? %>
   <% controller.redirect_to stats_show_path %>
  <% else %>
    <% controller.redirect_to users_show_path(:id => current_user) %>
  <% end %>
<% else %>

  <div class="center jumbotron">
    <div class="container">
      <div class="col-md-5">
      <%= link_to image_tag("boy-with-lightbulb.jpg", alt: "Curious Tots", size: "450x450") %>
      </div>
      <div class="col-md-7">
        <h1>Spark your child's curiosity!</h1>
        <h2>Sign up to receive a cool science fact every week!</h2>
        <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/static_pages/how_it_works.html.erb
  <div class="center jumbotron">
    <div class="container">
      <div class="col-md-6" valign="center">
        <br>
        <h3 align="left"><%= image_tag("signup.png", size: "32x32") %> &nbsp; Create a Curious Tots account.</h3>
        <br>
        <h3 align="left"><%= image_tag("child.png", size: "32x32") %> &nbsp; Tell us the name and age of your child.</h3>
        <br>
        <h3 align="left"><%= image_tag("email.png", size: "32x32") %> &nbsp; Receive weekly science fact emails.</h3>
        <br><br>
        <h5>Ready to try it out? <%= link_to "Sign up now!", signup_path %> </h5>
      </div>
       <div class="col-md-6">
        <%= image_tag('sample_email.png', size: "650x400") %>
      </div>
    </div>
  </div>