config/routes.rb
Rails.application.routes.draw do
 

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'histories/index'

  get 'references/new'
  get 'references/edit'
  get 'references/show'

  get 'stats/show'

  get 'facts/new'

  get 'children/new'

  get 'users/new'
  get 'users/create'
  get 'users/show'
  
  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy' 
  
  get   'how_it_works' => 'static_pages#how_it_works'
  get   'about' => 'static_pages#about'

  resources :users
  resources :children
  resources :facts
  resources :references, only: [:new, :create, :edit, :update, :index]
  resources :histories, only: [:index]
  resources :subscriptions, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  root 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :children
  
  attr_accessor :reset_token
  
  # save email in lower case
  before_save { self.email = email.downcase }
  
  # first and last name validations
  validates :fname, presence: true, length: {maximum:25}
  validates :lname, presence: true, length: {maximum:25}
  
  # email validations
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:255},
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: {case_sensitive: false}
  
  has_secure_password
  
  # validate password for min 6 characters and at least 1 number
  VALID_PASSWORD_REGEX = /.*[0-9]+.*/i
  validates :password, length: { minimum: 6 },
                 format: { with: VALID_PASSWORD_REGEX, message: " must contain at least 1 number" }, allow_blank: true
                 
  scope :admin, lambda { |admin| where(admin: admin) }

  # creates a digest, used to store a password digest in db
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                              BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end
  
  # Sends password reset email.
  def send_password_reset_email
    PasswordResetMailer.password_reset(self).deliver_now
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(token)
    digest = reset_digest
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]
  before_action :correct_user_or_admin, only: [:show]
  before_action :admin_user, only: [:index, :edit, :update]

  def new
    @user = User.new
    @new_admin = false
    @new_admin = true if params[:admin] == "true"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if @user.admin?
        redirect_to users_path(admin:true)
      else
        log_in(@user)
        WelcomeMailer.welcome_email(@user).deliver_now
        redirect_to new_child_url
      end
    else
      if @user.admin?
        @new_admin = true
      end
      render 'new'
    end
  end
  
  def edit
    @admin = User.find(params[:id])
  end
  
  def update
    @admin = User.find(params[:id])
    if @admin.update_attributes(user_params)
      flash[:success] = @admin.fname + " " + @admin.lname.possessive + " info has been updated!"
      redirect_to users_path(admin:true)
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @children = @user.children.order(:name)
  end
  
  def index
    @show_admins = nil
    if params[:admin] == "true"
      @users = User.admin(true)
      @show_admins = true
    else
      @users = User.admin(false)
      @show_admins = false
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:fname, :lname, :email, :password,
                                     :password_confirmation, :admin)
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end
    
    def correct_user_or_admin
      @user = User.find(params[:id])
      redirect_to root_url unless admin_user? || current_user?(@user)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>
  <%=user.fname%>
  <%=user.lname%>
  (
  <% if @show_admins %>
    <%= link_to user.email, edit_user_path(user.id) %>
  <% else %>
    <%=user.email%>
  <% end %>
  )
  <% if !@show_admins %>
    <%= link_to pluralize(user.children.count, "child"), user_path(user.id) %>
  <% end %>
</li>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit Administrator</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@admin) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.label :fname, "First Name" %>
      <%= f.text_field :fname, class: 'form-control'  %>

      <%= f.label :lname, "Last Name" %>
      <%= f.text_field :lname, class: 'form-control'  %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.hidden_field :admin, :value => true %>
      <%= f.submit "Update administrator", class: "btn btn-primary" %>
      
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% if @show_admins %>
  <h1>Administrators</h1>
  <%= link_to "New Administrator", new_user_path(admin: true) %>
<% else %>
  <h1>Users</h1>
<% end %>

<ul class="lined-list">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<% if @new_admin %>
  <h1>New Administrator</h1>
<% else %>
  <h1>Sign up</h1>
<% end %>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@user) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.label :fname, "First Name" %>
      <%= f.text_field :fname, class: 'form-control'  %>

      <%= f.label :lname, "Last Name" %>
      <%= f.text_field :lname, class: 'form-control'  %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <% if @new_admin %>
        <%= f.hidden_field :admin, :value => true %>
        <%= f.submit "Create administrator", class: "btn btn-primary" %>
      <% else %>
        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.fname%>'s Curious Tots: </h1>

<ul class="lined-list">
  <%= render @children %>
  <% if !admin_user? %>
    <%= link_to "Add child", controller: "children", action: "new" %>
  <% end %>
</ul>