config/routes.rb
Rails.application.routes.draw do
 

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'histories/index'

  get 'references/new'
  get 'references/edit'
  get 'references/show'

  get 'stats/show'

  get 'facts/new'

  get 'children/new'

  get 'users/new'
  get 'users/create'
  get 'users/show'
  
  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy' 
  
  get   'how_it_works' => 'static_pages#how_it_works'
  get   'about' => 'static_pages#about'

  resources :users
  resources :children
  resources :facts
  resources :references, only: [:new, :create, :edit, :update, :index]
  resources :histories, only: [:index]
  resources :subscriptions, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  root 'static_pages#home'

end

app/models/fact.rb
class Fact < ActiveRecord::Base
  
  belongs_to :reference
  
  # Constants
  CATEGORY_NATURE = "nature"
  CATEGORY_PHYSICAL_WORLD = "physical_world"
  CATEGORY_SPACE = "space"
  CATEGORY_VEHICLES = "vehicles"
  CATEGORY_BODY = "body"
  CATEGORY_DINOSAURS = "dinosaurs"
  CATEGORIES = [CATEGORY_NATURE, CATEGORY_PHYSICAL_WORLD, CATEGORY_SPACE, CATEGORY_VEHICLES, CATEGORY_BODY, CATEGORY_DINOSAURS]
  
  validates :content, presence: true, uniqueness: true
  validates :category, inclusion: { in: CATEGORIES}
  validates :age_low, presence: true, numericality: { only_integer: true }
  validates :age_high, presence: true, numericality: { only_integer: true }
  validates :age_low, numericality: {less_than_or_equal_to: :age_high}, unless: "age_high.nil? || age_low.nil?"
  
  # named scopes
  scope :active, lambda { |active| where(active_flag: active) }
  scope :category, lambda { |category| where(category: category) }
  scope :age, lambda { |age| where(":child_age BETWEEN age_low AND age_high", child_age: age) }
  
  def self.select_fact(child)
    history = "SELECT fact_id FROM histories where child_id = :child_id"
    age = ":child_age BETWEEN age_low AND age_high"
    active_flag = "active_flag = :active"
    Fact.where("id NOT IN (#{history}) AND #{active_flag} AND #{age}", child_id: child.id, child_age: child.age, active: true).order("RANDOM()").limit(1).first
  end
  
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user
  
  def new
      @fact = Fact.new
      @citations = Reference.all
  end
  
  def create
    
    @fact = Fact.new(fact_params)
    
    if @fact.save
      redirect_to facts_url
    else
      render 'new'
    end
  end
  
  def edit
    @fact = Fact.find(params[:id])
  end
  
  def update
    
    # find the fact to be updated based on :id attribute
    @fact = Fact.find(params[:id])
    
    if @fact.update_attributes(fact_params)
      flash[:success] = "Fact updated."
      redirect_to facts_url
    else
      render 'edit'
    end
  end
  
  def index
    @facts = nil
    case
      when params[:active_flag].present?
        @facts = Fact.active(eval(params[:active_flag]))
      when params[:age].present?
        @facts = Fact.age(eval(params[:age]))
      when params[:category].present?
        @facts = Fact.category(params[:category])
      else
        @facts = Fact.all
    end
    
    # stats
    @total_facts = Fact.count
    @active_facts = Fact.active(true).count
    @inactive_facts = Fact.active(false).count
    
    @age_counts = Array.new
    (Child::MIN_CHILD_AGE..Child::MAX_CHILD_AGE).each do |age|
      @age_counts.push(Fact.age(age).count)
    end
    
    @category_counts = Hash.new
    Fact::CATEGORIES.each do |category|
      @category_counts[category] = Fact.category(category).count
    end
    
  end
  
  def destroy
    Fact.find(params[:id]).destroy
    flash[:success] = "Fact deleted."
    redirect_to facts_url
  end
  
  private
    
    def fact_params
      params.require(:fact).permit(:content, :category, :age_low, :age_high, :reference_id, :active_flag)
    end
    
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/facts/_fact.html.erb
<tr>
<td><%= link_to "Fact #{fact.id}", edit_fact_path(fact.id) %></td>
<td width:50px; word-wrap: break-word><%=fact.content%></td>
<td><%=fact.category%></td>
<td><%=fact.age_low%> - <%=fact.age_high%></td>
<!--<td><%= link_to "delete", fact, method: :delete,
                                  data: { confirm: "You sure?" } %></td>-->
</tr>

app/views/facts/_stats.html.erb
<ul class="lined-list">

<li><%= link_to "Total (#{@total_facts})", facts_path, method: "get" %></li>

<li>  
<%=link_to "Active (#{@active_facts})", facts_path(active_flag:true), method: "get" %> <br>
<%=link_to "Inactive (#{@inactive_facts})", facts_path(active_flag:false), method: "get" %>
</li>

<li>
<% @age_counts.each_index do |index| %>
  <%= link_to "#{Child::MIN_CHILD_AGE + index} yo (#{@age_counts[index]})", facts_path(age: Child::MIN_CHILD_AGE + index), method: "get" %>
  <br>
<% end %>
</li>

<li>
<% @category_counts.each_pair do |category, count| %>
  <%= link_to "#{category} (#{count})", facts_path(category: category), method: "get" %>
  <br>
<% end %>
</li>
</ul>  

app/views/facts/edit.html.erb
<h1>Edit fact</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@fact) do |f| %>
      
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control'  %>
      
      <%= f.label "Age Range"%>
      <div class="row">
        <div class="col-md-2">
          <%= f.text_field :age_low%>
        </div>
        <div class="col-md-2">
           to 
        </div>
        <div class="col-xs-2">
          <%= f.text_field :age_high %>
        </div>
      </div>
      
      <%= f.label :category %>
      <%= f.select :category, options_for_select(Fact::CATEGORIES) %>
      
      <%= f.label :reference %>
      <%= f.select :reference_id, Reference.all.order(:citation).collect {|r| [r.citation, r.id]}, { include_blank: true } %>
            
      <%= f.label :active_flag, :class => "checkbox" do %>
         <%= f.check_box :active_flag %> Active
      <% end %>
            
      
      <%= f.submit "Save changes", class: "btn btn-primary" %>
      
    <% end %>
 </div>
</div>

app/views/facts/index.html.erb
<h1>Facts</h1>

<p><%= link_to "New Fact", new_fact_path, method: "get" %></p>

<div class="row">
    <aside class="col-md-2">
       <%= render 'facts/stats' %>
    </aside>
      
<div class="col-md-10">

<table id="facts">
  <tr>
    <th>#</th>
    <th>Content</th>
    <th>Category</th>
    <th>Age Range</th>
  </tr>
  <%= render @facts %>
</table>

</div>  

</div>  

app/views/facts/new.html.erb
<h1>Create a new fact</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@fact) do |f| %>
      
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control'  %>
      
      <%= f.label "Age Range"%>
      <div class="row">
        <div class="col-md-2">
          <%= f.text_field :age_low%>
        </div>
        <div class="col-md-2">
           to 
        </div>
        <div class="col-xs-2">
          <%= f.text_field :age_high %>
        </div>
      </div>
      
      <%= f.label :category %>
      <%= f.select :category, options_for_select(Fact::CATEGORIES) %>
      
      <%= f.label :reference %>
      <%= f.select :reference_id, Reference.all.order(:citation).collect {|r| [r.citation, r.id]}, { include_blank: true } %>
      
      <%= f.label :active_flag, :class => "checkbox" do %>
         <%= f.check_box :active_flag %> Active
      <% end %>
      
      
      
      <%= f.submit "Add fact", class: "btn btn-primary" %>
      
    <% end %>
 </div>
</div>