config/routes.rb
Rails.application.routes.draw do
 

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'histories/index'

  get 'references/new'
  get 'references/edit'
  get 'references/show'

  get 'stats/show'

  get 'facts/new'

  get 'children/new'

  get 'users/new'
  get 'users/create'
  get 'users/show'
  
  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy' 
  
  get   'how_it_works' => 'static_pages#how_it_works'
  get   'about' => 'static_pages#about'

  resources :users
  resources :children
  resources :facts
  resources :references, only: [:new, :create, :edit, :update, :index]
  resources :histories, only: [:index]
  resources :subscriptions, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  root 'static_pages#home'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Curious Tots", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        
        <% if logged_in? %>
          <% if admin_user? %>
            <li><%= link_to "Facts", facts_path, method: "get" %></li>
            <li><%= link_to "References", references_path, method: "get" %></li>
            <li><%= link_to "Admins", users_path(admin:true), method: "get" %></li>
            <li><%= link_to "Users", users_path, method: "get" %></li>
          <% end %>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%=link_to "How it works", how_it_works_path %></li>
          <li><%=link_to "About Us", about_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Curious Tots</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
</head>
<body>
   <%= render 'layouts/header' %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>

</body>
</html>